### ISSUE TITLE
I am using a workspace with west T2 topology, how should I add this sdk in my west.yml

### ISSUE THREAD

**Issue by lucsegers** [1NCE-GmbH/1nce-iot-c-sdk#11]
### Describe the issue

Hi,

I am using a workspace/ project according the west T2 topology([west T2 topology](https://docs.zephyrproject.org/latest/develop/west/workspaces.html#t2-star-topology-application-is-the-manifest-repository)).

How should I add the 1nce library to my west.yml? Should I make sure the module is loaded in modules/lib/nce-sdk folder?
I am a bit confused because you are basically manually manipulating the Zephyr west.yml etc.
In my case I would have to change my own west.yml

**Comment by lucsegers** [comment]
I think I found the solution for this. maybe this can be added to the documentation.

my west.yml file looks like this
```
manifest:
  self:
    path: application
  remotes:
    - name: nrf
      url-base: https://github.com/nrfconnect
    - name: nce
      url-base: https://github.com/1NCE-GmbH
  projects:
    - name: sdk-nrf
      remote: nrf
      path: nrf
      revision: v2.2.0
      import:
        path-prefix: external
      clone-depth: 1
    - name: 1nce-iot-c-sdk
      remote: nce
      path: external/modules/lib/1nce-iot-c-sdk
      revision: v3.0.0
      clone-depth: 1
```

this results in following structure of the project after doing `west init -m ...` :
```
west-workspace/
│
├── application/
│   ├── CMakeLists.txt
│   ├── prj.conf
│   ├── src/
│   │   └── main.c
│   └── west.yml         <--- this is the west.yml file for the application
│
└── external
    ├── modules/
    │   └── lib/
    │       └── 1nce-iot-c-sdk/
    │
    └── zephyr/
        └── west.yml
```

Copied CMakeLists.txt, prj.conf, Kconfig and main.c out of https://github.com/1NCE-GmbH/blueprint-zephyr/tree/main/nce_coap_demo and was able to build and run it.
